"""
phase3_zero.py — Ground Truth Baseline Report

Reads the rule set generated by phase1 (generated_rules.json) and reports
exactly how many rules of each overlap type exist and what structural
signature was used to produce them.

This is the answer key. Students compare their phase3_traditional.py
detection results against this output to measure accuracy.

Usage:
    python3 phase3_zero.py
    python3 phase3_zero.py --config config.yaml
    python3 phase3_zero.py --output report.json
"""

import json
import sys
from collections import defaultdict
from pathlib import Path

import click
import yaml
from rich.console import Console
from rich.table import Table

console = Console()

# ---------------------------------------------------------------------------
# Detection signature descriptions — shown in the report so students
# understand what structural property each type represents.
# ---------------------------------------------------------------------------

TYPE_SIGNATURES = {
    "shadow-broad": {
        "group":     "Shadow Rules",
        "role":      "Broad (catches traffic)",
        "signature": (
            "Placed before a narrower rule with the same service. "
            "Its src/dst address objects cover a wider range, so it "
            "matches all traffic the narrower rule would have matched."
        ),
    },
    "shadow-specific": {
        "group":     "Shadow Rules",
        "role":      "Narrow (unreachable)",
        "signature": (
            "Placed after a broader rule that covers its entire src/dst range. "
            "The FortiGate evaluates rules top-down and matches the broad rule "
            "first, so this rule is permanently unreachable."
        ),
    },
    "duplicate": {
        "group":     "Duplicate Rules",
        "role":      "Exact copy",
        "signature": (
            "Identical (srcaddr, dstaddr, service, action) tuple as another rule, "
            "different name and policy ID. Simulates copy-paste accumulation. "
            "Only the first matching rule ever fires."
        ),
    },
    "subnet-overlap-broad": {
        "group":     "Subnet Overlap",
        "role":      "Broad /24",
        "signature": (
            "A /24 permit rule whose source address range fully contains the "
            "source address of the specific rule below it. Makes the specific "
            "rule redundant for all traffic that matches the broad range."
        ),
    },
    "subnet-overlap-specific": {
        "group":     "Subnet Overlap",
        "role":      "Specific /28 or /32 (redundant)",
        "signature": (
            "A narrower rule (/28 or /32) whose source is entirely contained "
            "within the broader /24 rule above it. Any traffic matching this "
            "rule is already permitted by the broader rule."
        ),
    },
    "svc-overlap": {
        "group":     "Collapsible Service Rules",
        "role":      "One service per rule",
        "signature": (
            "Same (srcaddr, dstaddr) pair as two or more sibling rules, each "
            "with a different service. Could be collapsed into a single rule "
            "with a service group, reducing policy count."
        ),
    },
    "clean": {
        "group":     "Clean Rules",
        "role":      "No overlap",
        "signature": (
            "No overlap with any other rule. Included to make the policy set "
            "non-trivially obvious — students must work to find the bad rules."
        ),
    },
}


# ---------------------------------------------------------------------------
# Loader
# ---------------------------------------------------------------------------

def load_rules(rules_file: str) -> tuple[list[dict], dict]:
    path = Path(rules_file)
    if not path.exists():
        console.print(f"[bold red]Rules file not found: {rules_file}")
        console.print("Run phase1 first:  python3 main.py rules --count 100")
        sys.exit(1)

    with open(path) as f:
        data = json.load(f)

    policies = data.get("policies", [])
    metadata = data.get("metadata", {})
    return policies, metadata


# ---------------------------------------------------------------------------
# Analysis
# ---------------------------------------------------------------------------

def analyze(policies: list[dict]) -> dict:
    """
    Count policies by _type and group shadow/subnet pairs so the report
    can show paired relationships clearly.
    """
    by_type: dict[str, list[dict]] = defaultdict(list)
    for p in policies:
        t = p.get("_type", "unknown")
        by_type[t].append(p)

    # Group shadow pairs by sequential position:
    # each LAB-BROAD-N is paired with the LAB-SHADOW-N+1 that immediately follows it.
    shadow_pairs = _pair_shadow_rules(by_type)

    # Group duplicate pairs: same (src, dst, svc) → group together
    dup_groups = _group_duplicates(by_type)

    # Group service-overlap clusters: same (src, dst) → group together
    svc_groups = _group_service_overlaps(by_type)

    # Group subnet overlap pairs
    subnet_pairs = _pair_subnet_overlaps(by_type)

    return {
        "by_type":      dict(by_type),
        "shadow_pairs": shadow_pairs,
        "dup_groups":   dup_groups,
        "svc_groups":   svc_groups,
        "subnet_pairs": subnet_pairs,
    }


def _pair_shadow_rules(by_type: dict) -> list[tuple[dict, dict]]:
    """Pair each shadow-broad with its shadow-specific by _seq order."""
    broads    = sorted(by_type.get("shadow-broad",    []), key=lambda p: p.get("_seq", 0))
    specifics = sorted(by_type.get("shadow-specific", []), key=lambda p: p.get("_seq", 0))
    return list(zip(broads, specifics))


def _group_duplicates(by_type: dict) -> list[list[dict]]:
    """Group duplicate rules by their (srcaddr, dstaddr, service) tuple."""
    groups: dict[tuple, list[dict]] = defaultdict(list)
    for p in by_type.get("duplicate", []):
        key = (
            tuple(a["name"] for a in p.get("srcaddr", [])),
            tuple(a["name"] for a in p.get("dstaddr", [])),
            tuple(s["name"] for s in p.get("service", [])),
        )
        groups[key].append(p)
    return [g for g in groups.values() if len(g) > 1]


def _group_service_overlaps(by_type: dict) -> list[list[dict]]:
    """Group svc-overlap rules by their (srcaddr, dstaddr) pair."""
    groups: dict[tuple, list[dict]] = defaultdict(list)
    for p in by_type.get("svc-overlap", []):
        key = (
            tuple(a["name"] for a in p.get("srcaddr", [])),
            tuple(a["name"] for a in p.get("dstaddr", [])),
        )
        groups[key].append(p)
    return [g for g in groups.values() if len(g) > 1]


def _pair_subnet_overlaps(by_type: dict) -> list[tuple[dict, dict]]:
    """Pair each subnet-overlap-broad with its subnet-overlap-specific by _seq."""
    broads    = sorted(by_type.get("subnet-overlap-broad",    []), key=lambda p: p.get("_seq", 0))
    specifics = sorted(by_type.get("subnet-overlap-specific", []), key=lambda p: p.get("_seq", 0))
    return list(zip(broads, specifics))


# ---------------------------------------------------------------------------
# Report
# ---------------------------------------------------------------------------

def print_report(policies: list[dict], metadata: dict, results: dict):
    total = metadata.get("total_pushed", len(policies))

    console.rule("[bold cyan]Phase 3 — Zero: Ground Truth Baseline")
    console.print(f"Rules file contains [bold]{total}[/bold] policies total.\n")

    # ── Summary table ────────────────────────────────────────────────────────
    summary = Table(title="Rule Type Summary", show_lines=True)
    summary.add_column("Group",            style="cyan",   min_width=24)
    summary.add_column("Type",             style="white",  min_width=22)
    summary.add_column("Count",            style="yellow", justify="right")
    summary.add_column("Detection Signature", style="white", min_width=52)

    for type_key, info in TYPE_SIGNATURES.items():
        count = len(results["by_type"].get(type_key, []))
        summary.add_row(
            info["group"],
            info["role"],
            str(count),
            info["signature"],
        )

    console.print(summary)

    # ── Shadow pairs ─────────────────────────────────────────────────────────
    if results["shadow_pairs"]:
        console.print(f"\n[bold yellow]Shadow Rule Pairs ({len(results['shadow_pairs'])} pairs)[/bold yellow]")
        t = Table(show_lines=True)
        t.add_column("Broad rule (catches traffic)", style="green")
        t.add_column("Shadowed rule (unreachable)",  style="red")
        t.add_column("Service", style="cyan")
        for broad, specific in results["shadow_pairs"]:
            svc = broad.get("service", [{}])[0].get("name", "?")
            t.add_row(broad["name"], specific["name"], svc)
        console.print(t)

    # ── Duplicate groups ─────────────────────────────────────────────────────
    if results["dup_groups"]:
        console.print(f"\n[bold yellow]Duplicate Groups ({len(results['dup_groups'])} groups)[/bold yellow]")
        t = Table(show_lines=True)
        t.add_column("Rule name",  style="white")
        t.add_column("Src",        style="cyan")
        t.add_column("Dst",        style="cyan")
        t.add_column("Service",    style="cyan")
        for group in results["dup_groups"]:
            for p in group:
                src = p.get("srcaddr", [{}])[0].get("name", "?")
                dst = p.get("dstaddr", [{}])[0].get("name", "?")
                svc = p.get("service", [{}])[0].get("name", "?")
                t.add_row(p["name"], src, dst, svc)
            t.add_section()
        console.print(t)

    # ── Service overlap clusters ─────────────────────────────────────────────
    if results["svc_groups"]:
        console.print(f"\n[bold yellow]Collapsible Service Groups ({len(results['svc_groups'])} clusters)[/bold yellow]")
        t = Table(show_lines=True)
        t.add_column("Rule name", style="white")
        t.add_column("Src",       style="cyan")
        t.add_column("Dst",       style="cyan")
        t.add_column("Service",   style="cyan")
        for group in results["svc_groups"]:
            for p in group:
                src = p.get("srcaddr", [{}])[0].get("name", "?")
                dst = p.get("dstaddr", [{}])[0].get("name", "?")
                svc = p.get("service", [{}])[0].get("name", "?")
                t.add_row(p["name"], src, dst, svc)
            t.add_section()
        console.print(t)

    # ── Subnet overlap pairs ─────────────────────────────────────────────────
    if results["subnet_pairs"]:
        console.print(f"\n[bold yellow]Subnet Overlap Pairs ({len(results['subnet_pairs'])} pairs)[/bold yellow]")
        t = Table(show_lines=True)
        t.add_column("Broad /24 rule",       style="green")
        t.add_column("Broad src",            style="cyan")
        t.add_column("Specific /28-32 rule", style="red")
        t.add_column("Specific src",         style="cyan")
        t.add_column("Service",              style="cyan")
        for broad, specific in results["subnet_pairs"]:
            broad_src = broad.get("srcaddr",    [{}])[0].get("name", "?")
            spec_src  = specific.get("srcaddr", [{}])[0].get("name", "?")
            svc       = broad.get("service",    [{}])[0].get("name", "?")
            t.add_row(broad["name"], broad_src, specific["name"], spec_src, svc)
        console.print(t)

    # ── Totals ───────────────────────────────────────────────────────────────
    n_problematic = total - len(results["by_type"].get("clean", []))
    console.print(
        f"\n[bold]Total:[/bold] {total} rules — "
        f"[green]{len(results['by_type'].get('clean', []))} clean[/green], "
        f"[red]{n_problematic} with overlap/redundancy issues[/red]"
    )
    console.print(
        "\n[dim]This is the ground truth. "
        "Compare your phase3_traditional.py output against these numbers.[/dim]"
    )


# ---------------------------------------------------------------------------
# JSON output
# ---------------------------------------------------------------------------

def build_json_report(metadata: dict, results: dict) -> dict:
    counts = {t: len(v) for t, v in results["by_type"].items()}
    return {
        "source":   "phase3_zero",
        "metadata": metadata,
        "counts":   counts,
        "shadow_pairs": [
            {"broad": b["name"], "shadowed": s["name"]}
            for b, s in results["shadow_pairs"]
        ],
        "duplicate_groups": [
            [p["name"] for p in g] for g in results["dup_groups"]
        ],
        "service_overlap_groups": [
            [p["name"] for p in g] for g in results["svc_groups"]
        ],
        "subnet_overlap_pairs": [
            {"broad": b["name"], "specific": s["name"]}
            for b, s in results["subnet_pairs"]
        ],
    }


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

@click.command()
@click.option("--config",  default="config.yaml",
              help="Path to config.yaml", show_default=True)
@click.option("--output",  default=None,
              help="Optional path to write JSON report")
def main(config, output):
    """
    Ground truth baseline: read phase1 rules and report each overlap type.
    No FortiGate or FortiAnalyzer connection required.
    """
    with open(config) as f:
        cfg = yaml.safe_load(f)

    rules_file = str(
        Path(cfg["lab"]["output_dir"]) / cfg["lab"]["rules_backup_file"]
    )

    policies, metadata = load_rules(rules_file)
    results = analyze(policies)
    print_report(policies, metadata, results)

    if output:
        report = build_json_report(metadata, results)
        Path(output).write_text(json.dumps(report, indent=2))
        console.print(f"\n[green]JSON report saved: {output}")


if __name__ == "__main__":
    main()
